substrait-io/substrait-rs

.gitignore
Cargo.lock
Cargo.toml
src/lib.rs

It turns out that I had already published a 0.1.0 version to crates.io some time ago (https://crates.io/crates/substrait/0.1.0)
This PR bumps the version to 0.2.0 and updates the substrait submodule to pick up the latest .proto files. Once this is merged I will publish the new version.

Use latest substrait & bump crate version

---

.github/dependabot.yml
.github/workflows/cron.yml
.github/workflows/docs.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
src/lib.rs

This PR adds some GitHub actions workflows for testing, doc deployment (`main` branch instead of release on `docs.rs`) and cron jobs (`cargo-audit`). In addition it adds a Dependabot configuration file to automate dependency updates (`cargo`, `git submodules` and `github actions`). This PR also updates the current dependencies of this project.
An example [run](https://github.com/mbrobbel/substrait-rs/actions/runs/3089538992) and [docs deployment](https://mbrobbel.github.io/substrait-rs/substrait/) on my fork.

Setup GitHub actions and Dependabot

---

.github/workflows/docs.yml
.github/workflows/test.yml

This should prevent:
```
Error: API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

Add repo-token to setup-protoc action to avoid rate limiting

---

.github/workflows/docs.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
build.rs
src/lib.rs

This adds an optional `pbjson` feature that uses [pbjson](https://github.com/influxdata/pbjson) to add `Serialize` and `Deserialize` implementations based on the [Protobuf JSON mapping](https://developers.google.com/protocol-buffers/docs/proto3#json).
I've also refactored the `build.rs` file to use the `walkdir` crate (instead of `glob`), and use `std::path` types instead of strings.
This builds on #5 ~and relies on https://github.com/influxdata/pbjson/pull/67,~ ~so marking this as draft for now.~

Add `pbjson` feature for Protobuf JSON serde

---

.github/dependabot.yml

It seems that with the current configuration we missed the release (https://github.com/substrait-io/substrait-rs/pull/13). It seems the release cron job of Substrait typically gets scheduled with a delay, so this PR changes the schedule to trigger 4 hours after the specified release cron job of Substrait.

Change schedule time for Dependabot submodule updates

---

Cargo.toml

Since the release workflow was broken 0.10.0 was pushed to crates.io, but the commit with changelog and version bump was not pushed to main. This fixes the version to make sure the next smart release can bump to 0.11.0.

chore: bump version to 0.10.0 to fix smart release

---

.github/workflows/docs.yml
README.md

Change required to handle the [failed deploy job](https://github.com/substrait-io/substrait-rs/actions/runs/5438507514/jobs/9889794289). Caused by a change in the `upload-pages-artifact` action: https://github.com/actions/upload-pages-artifact#file-permissions. Also added an index file that redirects the client to the substrait crate docs.

chore(ci): fix doc deployment file permissions

---

CONTRIBUTING.md

We no longer use bors (#103)  and the merge workflow was removed as part of that change.

chore: update `CONTRIBUTING.md` to reflect workflow changes

---

.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/test.yml
CHANGELOG.md
Cargo.toml
build.rs
src/lib.rs
src/proto.rs

- Removes `serde` support for the generated proto types
- Uses `pbjson` ser/de when the `serde` feature is enabled.
- Removes the `pbjson` feature.
Closes #158.

refactor!: remove `serde` support for `proto` types

---

.github/workflows/release.yml

With the addition of a cache in the release workflow we need to handle the case where the tool is already installed.

fix(ci): release job cargo install cache hit

---

Cargo.toml
build.rs
src/lib.rs
src/parse/context.rs
src/parse/mod.rs
src/parse/proto/mod.rs
src/parse/proto/version.rs
src/version.rs

This adds the `parse` module with the `Parse` and `Context` traits, and a parser for `proto::Version`. The `Context` trait will be extended when needed for the specific parsers that require it.

feat(parse)!: add `parse` module and `proto::Version` parser

---

.github/workflows/release.yml
src/parse/context.rs
src/parse/proto/mod.rs
src/parse/proto/plan_version.rs
src/parse/proto/version.rs
src/proto.rs
src/text.rs

A parser for `proto::PlanVersion`, it parses iff the version is not missing and the version parses.

feat(parse): add `proto::PlanVersion` parser

---

Cargo.toml
src/parse/context.rs
src/parse/mod.rs
src/parse/proto/extensions/mod.rs
src/parse/proto/extensions/simple_extension_uri.rs
src/parse/proto/mod.rs
src/parse/proto/plan_version.rs
src/parse/proto/version.rs
src/parse/text/mod.rs
src/parse/text/simple_extensions/mod.rs
src/parse/typed.rs

Adds a parser for `proto::extensions::SimpleExtensionUri` that parses the uri and adds the extension to the parse context. 
Breaking change because the parse `Context` trait gets two new functions to support this:
- `add_simple_extension_uri`: this is used to add a simple extensions, the parse context must directly resolve the uri and return the parsed simple extensions - struct stub for that is added in this PR (the parser is TODO).
- `simple_extensions`: given an reference (anchor) to a simple extensions - check if this was added to the parse context and return it

feat(parse)!: add `proto::extensions::SimpleExtensionUri` parser

---

Cargo.toml
build.rs
src/version.rs

Same idea as #173, except this directly calls `git describe` at build time (when there is a submodule).

feat: directly call `git` to get substrait submodule version

---

build.rs

Follow-up of #175: the `version` variable was shadowed resulting in the wrong value for `SUBSTRAIT_GIT_DESCRIBE`.

fix: fix `SUBSTRAIT_GIT_DESCRIBE` value

---

build.rs

This PR introduces the possibility of building the library from protobuf definitions that are symbolically linked. Closes #180

fix: support generating protos from symlinks

---

Cargo.toml
build.rs
src/extensions.rs
src/lib.rs
src/text.rs

Include core extensions from `Subtrait`.
The majority of the code originates from the un-merged pr #89.
The generated code:
```rust
// SPDX-License-Identifier: Apache-2.0
// Note that this file is auto-generated and auto-synced using `build.rs`. It is
// included in `extensions.rs`.
/// Included source of [`functions_datetime`](https://github.com/substrait-io/substrait/raw/v0.48.0/extensions/functions_datetime.yaml).
const FUNCTIONS_DATETIME: &str = include_str!("/Users/awfover/Projects/substrait-rs/substrait/extensions/functions_datetime.yaml");
/// Included source of [`functions_comparison`](https://github.com/substrait-io/substrait/raw/v0.48.0/extensions/functions_comparison.yaml).
const FUNCTIONS_COMPARISON: &str = include_str!("/Users/awfover/Projects/substrait-rs/substrait/extensions …
```

feat(extensions): include Substrait core extensions

---

src/parse/text/simple_extensions/argument.rs
src/parse/text/simple_extensions/mod.rs

Adds a parser for `text::simple_extensions::ArgumentsItem` that parses the argument.

feat(parse): add `text::simple_extensions::ArgumentsItem` parser

---

Cargo.toml

tonic 0.12 depends on prost 0.13

build(deps)!: upgrade prost to 0.13 for hyper 1.x

---

.github/dependabot.yml

This groups the dependabot updates of these packages together.

chore: add `prost` and `pbjson` dependabot groups

---

.github/workflows/docs.yml
CONTRIBUTING.md
Cargo.toml
src/parse/proto/extensions/mod.rs
src/proto.rs

It's no longer required to specify this in our package metadata.

docs: `--cfg=docsrs` is now a default set by docs.rs

---

.github/workflows/release.yml

The smart-release lock file is pointing to an outdated version of `time` that fails to build on the latest stable rustc. Reverting to the previous stable release until the next smart-release release.

ci: use previous rust release to build smart release with lock file

---

Cargo.lock
Cargo.toml

Reverts substrait-io/substrait-rs#226. The release was yanked.

chore(deps,cargo): revert bump once_cell from 1.19.0 to 1.20.0 in the cargo group

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
build.rs
src/extensions.rs
src/proto.rs

Removes the `once_cell` dependency, replacing it with `std::sync::LazyLock`, stabilized in Rust `1.80`.

refactor: replace `once_cell` with `std::sync::LazyLock`, bumping msrv to `1.80.1`

---

.github/workflows/release.yml
release-plz.toml

This gives us a release PR that triggers a new release when merged, instead of always releasing on push to main. The goal is not to reduce the release frequency, but to skip releases on `Cargo.lock` changes, because these releases are useless for dependents.

ci(release): use `release-plz`

---

.github/workflows/release.yml
release-plz.toml

We need to run the build script to generate version information:
https://github.com/substrait-io/substrait-rs/blob/a54d8ecaf853d4104e28668010666bd9b7cb7c02/src/version.rs#L11
This also means we need to set `publish_allow_dirty` to make the published package include those generated files.

fix(release): trigger build script before release

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Reverts substrait-io/substrait-rs#288. The release job failed. This should trigger a retry (new PR) with the fix from #291 when merged to main.

chore: undo release v0.53.0

---

.github/workflows/release.yml

`substrait` submodule update commits currently don't trigger a release PR. This is an attempt to fix that.

chore(release): update generated files before running release-plz

---

build.rs
release-plz.toml

We want release-plz to trigger a version bump when we change the substrait version. Because we generate files it seems that is's not always picking that up correct (e.g. when it's just a documentation change - which could be breaking). This reverts #331.

feat!: add substrait version const to trigger semver check on substrait update
